### ISSUE TITLE
Not Launching in Safari

### ISSUE THREAD

**Issue by sampoder** [hackclub/live-editor#1]
I know some computers in my school only have Safari, so running workshops might be a difficulty 

<img width="1439" alt="Screenshot 2021-11-03 at 5 51 34 PM" src="https://user-images.githubusercontent.com/39828164/140039554-5a79783f-2c90-4bcf-864d-60e4f0919ba9.png">

**Comment by leomcelroy** [comment]
I think this was my use of experimental import maps. Try it now, I took that out.

**Comment by sampoder** [comment]
Awesome, it has been fixed!
